<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cfg</string>
		<string>pcf</string>
		<string>ucf</string>
	</array>
	<key>name</key>
	<string>Bentley Config Files</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#VarDefRef</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>#.*</string>
			<key>name</key>
			<string>comment.line.number-sign.bentleyConfig</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.bentleyConfig</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Levels</string>
			<key>match</key>
			<string>%\s*level\s+([0-9]{1})</string>
			<key>name</key>
			<string>keyword.other.bentleyConfig</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.bentleyConfig</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>VarDef</string>
			<key>match</key>
			<string>^\s*[a-zA-Z0-9_]*\s*(=|:|&lt;|&gt;|\+)</string>
			<key>name</key>
			<string>variable.other.bentleyConfig</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Flow control</string>
			<key>match</key>
			<string>%\s*(if|else|elif|endif|ifdef)\s+</string>
			<key>name</key>
			<string>keyword.control.bentleyConfig</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>%\s*include\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.bentleyConfig</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Include</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>source.bentleyConfig</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#VarDefRef</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.bentleyConfig</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Levels</string>
					<key>match</key>
					<string>level\s+([0-9]{1})</string>
					<key>name</key>
					<string>keyword.other.bentleyConfig</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Error</string>
			<key>match</key>
			<string>%\s*error\s+</string>
			<key>name</key>
			<string>keyword.control.bentleyConfig</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.bentleyConfig</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Undef / Lock</string>
			<key>match</key>
			<string>%\s*(undef|lock)\s*([a-zA-Z0-9_]+)</string>
			<key>name</key>
			<string>keyword.control.bentleyConfig</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>((defined|exists)\s*\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.bentleyConfig</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.bentleyConfig</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.bentleyConfig</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#VarDefRef</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ConfigVar</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>ConfigVar</key>
		<dict>
			<key>match</key>
			<string>[a-zA-Z0-9_]+</string>
			<key>name</key>
			<string>variable.parameter.bentleyConfig</string>
		</dict>
		<key>VarDefRef</key>
		<dict>
			<key>begin</key>
			<string>\$[\(\{]</string>
			<key>comment</key>
			<string>Variable Definition References</string>
			<key>end</key>
			<string>[\)\}]</string>
			<key>name</key>
			<string>string.interpolated.bentleyConfig</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ConfigVar</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(dev|dir|devdir|parentdir|parentdevdir|basename|filename|ext|noext|first|concat|build)\s*[\(\{]</string>
					<key>end</key>
					<string>[\)\}]</string>
					<key>name</key>
					<string>keyword.control.bentleyConfig</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#ConfigVar</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.bentleyConfig</string>
	<key>uuid</key>
	<string>4f7d61f2-6b40-47cf-89e0-ecc5f86d5fe8</string>
</dict>
</plist>
